### ISSUE TITLE
hvac-schedule not working

### ISSUE THREAD

**Issue by mapa0402** [node-red-contrib/node-red-contrib-renault-ze#101]
**Describe the bug**
Trying with hvac-schedule to start warming of the car.

**To Reproduce**
use inject node with msg.topic set to "hvac-schedule"

**Expected behavior**
Warmer car :)

**Version (please complete the following information):**
1.4.2
docker container nodered/node-red:latest-16

**Additional context**
message: "{"errors":[{"status":"Not Implemented","code":"501","title":"Not supported Feature","detail":"This feature is not technically supported by this gateway"}]}"

**Comment by konne** [comment]
hi @mapa0402 

not all api commands work with all cars and for example for me the hvac is since one year only working if the car is connected to a wallbox.
Does it work for you from the renault app?

**Comment by mapa0402** [comment]
hi, yes it works with the official renault app, and when I use the open-source Z.E. Services. That app seems to use "hvac-start" and maybe other services than this library?
https://github.com/chrisstaite/ZEServices/blob/master/zecommon/src/main/java/com/yourdreamnet/zecommon/api/Vehicle.kt

**Comment by konne** [comment]
@mapa040you need to use set-hvac-state see
https://github.com/node-red-contrib/node-red-contrib-renault-ze/blob/main/src/renault-ze.ts#L67C33-L67C59
with a temperature so just take 21 as temp

**Comment by mapa0402** [comment]
> @mapa040you need to use set-hvac-state see https://github.com/node-red-contrib/node-red-contrib-renault-ze/blob/main/src/renault-ze.ts#L67C33-L67C59 with a temperature so just take 21 as temp

that seems to do the task, thank you!
