### ISSUE TITLE
TypeError: Cannot read property 'cookieValue' of undefined from Renault-ze node

### ISSUE THREAD

**Issue by ronvanewijk** [node-red-contrib/node-red-contrib-renault-ze#105]
**Describe the bug**

**To Reproduce**

1. Go to 'basic flow', add email and password
2. Click on 'inject'
3. Go to 'debug node'
4. See error: "TypeError: Cannot read property 'cookieValue' of undefined"

**Expected behavior**
data from API

**Screenshots**
![renault-ze](https://github.com/node-red-contrib/node-red-contrib-renault-ze/assets/17528133/b2cb0cf9-b092-47a0-85aa-b8fce81d417f)

**Version (please complete the following information):**

- OS: win11
- Browser: Chrome
- Node-Red: 1.1.3

**Additional context**
If I go to "http://services.renault-ze.com/user/login" page not found!

**Comment by konne** [comment]
maybe an issue with country / car type. for it it is just normal working
