### ISSUE TITLE
Mileage not working anymore

### ISSUE THREAD

**Issue by JapieG** [node-red-contrib/node-red-contrib-renault-ze#106]
since 12:00 today mileage is not retrieving anymore. (/cockpit endpoint)

It gives me this message back:

message: "you should not be there but well done for the effort"

Any ideas?

**Comment by JapieG** [comment]
https://github.com/hacf-fr/renault-api/issues/1135

**Comment by JapieG** [comment]
https://tweakers.net/i/_cjZywu5Df-hGipXXDfp2j5M3eU=/full-fit-in/4920x3264/filters:max_bytes(3145728):no_upscale():strip_icc():fill(white):strip_exif()/f/image/a7zJHmf6J0LP7rFKQEpO2jYe.jpg?f=user_large

comment the line as shown in the picture to force v1 of the API endpoint and it works again.

**Comment by tetti-de** [comment]
Many thanks to **JapieG**, the change worked.

**Comment by JapieG** [comment]
> Many thanks to **JapieG**, the change worked.

The credits go to @eltoro0815

**Comment by konne** [comment]
@JapieG @tetti-de @eltoro0815 
thanks for highlighting and pointing to the issue.
This is fixed in the newest version: [1.4.3](https://github.com/node-red-contrib/node-red-contrib-renault-ze/releases/tag/1.4.3)
