### ISSUE TITLE
charge-schedule 400 bad request

### ISSUE THREAD

**Issue by Gaetanb76** [node-red-contrib/node-red-contrib-renault-ze#160]
**Describe the bug**
I copy/paste the code
I set my username and pwd
When I try hvac-schedule, this debug message appear :
`object
_msgid: "bb3e7251d65eee8b"
topic: "charge-schedule"
payload: object
type: "FUNCTIONAL"
messages: array[1]
errors: array[1]
0: object
errorCode: "err.func.vcps.ev.charge-schedule.error"
errorMessage: "{"errors":[{"errorCode":"400 BAD_REQUEST","errorMessage":"400 Bad Request: \"{\"errors\":[{\"errorCode\":\"400002\",\"errorMessage\":\"For vnext vehicles, call endpoint: /v1/vehicles/{vin}/charging-settings\",\"errorLevel\":\"error\",\"errorType\":\"functional\"}],\"error_reference\":\"bbdfa0b8-25e8-4007-afbf-3f26ca18f0dc2016065\"}\"","errorLevel":"error","errorType":"technical"}],"error_reference":"a243ebd3-f16a-4704-bec4-4c672c3c616f3116402"}"
error_reference: "FUNCTIONAL"`

**Version (please complete the following information):**

OS: Windows 11
    Browser: Firefox 132.0.1
    Node-Red: 3.02

**Comment by konne** [comment]
close because copy of #159

**Comment by Gaetanb76** [comment]
Hi,
This issue was for the charge-schedule.
The #[https://github.com/node-red-contrib/node-red-contrib-renault-ze/issues/159] is for the hvac-schedule
