### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by konne** [node-red-contrib/node-red-contrib-renault-ze#2]
Hi you already wrote that you have no access and can not implement the needed changes. 

I can now make a new repo and a new npm but this pollute the packages.
Can you please answer on my request:

@watchforstock would it be okay for you if you transfer the repo and the npm package to me so that I can make the rework and take care of publishing new releases.

**Comment by watchforstock** [comment]
Hi @konne 
It makes sense to transfer the npm package, or perhaps rather make you a maintainer. As the git repo is under my username, it probably makes sense for you to make a new one of those under your account, whether you do it from a fork of this one or not is up to you.

If you can let me know your npm username I can add you as a maintainer on the package there

Thanks

Andrew

**Comment by konne** [comment]
Hi Andrew, 

I have the same username on github and npm (konne).
If you go in the repository settings you will find the point "transfer"
So you could even just transfer the existing project of your repo
if you like. I added a new org "node-red-contrib" there will collect
and maintain the projects.  Because of the TEAM I can than also add
you as a maintainer of the repo.
The cool think about the transfer is that GitHub still generates a hidden
redirect from the current URL of the project to the new one.

Just write what is you discission and I will use the transferred project
or just make an fork/new one.
Please write to me also if you added me to the npm.

bye
Konrad

**Comment by watchforstock** [comment]
Hi Konrad,

I have attempted to transfer the repository to you (I think you need to accept it). I have also added you as a maintainer with write access to NPM

Thanks

Andrew

**Comment by konne** [comment]
@watchforstock thanks. I will take care that we have soon again a working version.
