### ISSUE TITLE
ZE services not working anymore

### ISSUE THREAD

**Issue by fischifischi** [node-red-contrib/node-red-contrib-renault-ze#20]
Since 01.02.2020 the node is not working anymore due API key change. The new kamareon key is "Ae9FDWugRxZQAGm3Sxgk7uJn6Q4CGEA2" as discussed here:
https://gist.github.com/mountbatt/772e4512089802a2aa2622058dd1ded7

**Comment by konne** [comment]
@fischifischi thanks.
At the moment I tried to fetch the data directly from a published JSON.
I will create today a new release with this hard coded API key.

**Comment by konne** [comment]
@fischifischi please check version 1.2.0

**Comment by fischifischi** [comment]
@konne  yes, works again. Thank you!
