### ISSUE TITLE
accounts.accounts is not iterable

### ISSUE THREAD

**Issue by YanK-fr** [node-red-contrib/node-red-contrib-renault-ze#22]
Hello,

First of all thank you for this work. :)
Everything has been going well for a few days.

Since yesterday I have this error: **[renault-ze: Zoé] TypeError: accounts.accounts is not iterable**

I have not been able to find the solution.
Maybe the API keys have changed or the authentication system is not the same.

Do you have an idea ?
Thank you in advance

**Comment by konne** [comment]
please see ticket #20
