### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by hassech** [node-red-contrib/node-red-contrib-renault-ze#24]
Since midday I get the following error:

TypeError: Cannot read property 'split' of undefined

Up until that time everything worked fine.

- OS: raspberry / raspbian Linux pi1 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
- Browser: firefox
- Node-Red: 1.0.3

Any halp? Many thanks in advance.

**Comment by konne** [comment]
@hassech thanks. I seems that renault is changing again something in the API.
I will try so solve it ASAP
I have the same issue

**Comment by konne** [comment]
@hassech should be fixed in the new 1.2.1 Release

**Comment by hassech** [comment]
@konne , it works again. Many thanks
