### ISSUE TITLE
cookie

### ISSUE THREAD

**Issue by Joker7555** [node-red-contrib/node-red-contrib-renault-ze#27]
Node Red:
"TypeError: Cannot read property 'cookieValue' of undefined"
if I click on one of th efour input nodes

Windows 10
Chrome

**Comment by konne** [comment]
@Joker7555 can you please describe this in more detail.
node-red version
node-red-contrib-renault-ze version

Screenshot,..

thx

**Comment by Joker7555** [comment]
Hello,
Thanks for answering

Node red Version  1.2.7
Renault                  1.2.1

P
It just pop up in my thoughts perhaps it has to do that we in the Netherlands must agree with cookiests??
See also cookie screen




Thanks for your support and time,
//Sjakie
On 22-2-2021 10:33:28, Konrad Mattheis <notifications@github.com> wrote:
@Joker7555 [https://github.com/Joker7555] can you please describe this in more detail.
node-red version
node-red-contrib-renault-ze version
Screenshot,..
thx

**Comment by konne** [comment]
Hi,

your login process doesn't work. But for me and other users, it works.

https://github.com/node-red-contrib/node-red-contrib-renault-ze/blob/b90f99742c9661ca9693f62a9c7b2eefc59933a0/src/ZEServices.ts#L342 

Can you maybe change your credentials with a password with only a-zA-Z0-9 to 
check if a special character makes an issue.

bye

**Comment by Joker7555** [comment]
Hi,
Pasword modified in smaal and big caps>> no luck error stays.

As mentioned in the Netherlands I must first click agree for cookies before I can access the field to enter my name and password.
//Sjakie

On 22-2-2021 13:54:05, Konrad Mattheis <notifications@github.com> wrote:
Hi,
your login process doesn't work. But for me and other users, it works.
https://github.com/node-red-contrib/node-red-contrib-renault-ze/blob/b90f99742c9661ca9693f62a9c7b2eefc59933a0/src/ZEServices.ts#L342 [https://github.com/node-red-contrib/node-red-contrib-renault-ze/blob/b90f99742c9661ca9693f62a9c7b2eefc59933a0/src/ZEServices.ts#L342]
Can you maybe change your credentials with a password with only a-zA-Z0-9 to
check if a special character makes an issue.
bye

**Comment by konne** [comment]
@Joker7555 I'm very sure that is not related to the cookie window.
We can try to make a screen share together and I can have a look at
the issue. Can you provide me an email address there I can send the invite
bye

**Comment by Kai-Angne** [comment]
Hi, i have the same problem as Joker7555.
"TypeError: Cannot read property 'cookieValue' of undefined"
Node Red Version 1.2.9 and node-red-contrib-renault-ze 1.2.1

My Flow worked before with the same credentials and without any other changes in between - except updates of node red and as far as i remember your Node was updated too.  

I get this error message when using any topic - BUT sometimes one of my flows with topic "cockpit" retrieves data.

Maybe this helps ...
Kai

**Comment by konne** [comment]
@Kai-Angne & @Joker7555 the good thing is that I have now the same issue and I can debug it. I will give you today an update.

**Comment by konne** [comment]
@Kai-Angne & @Joker7555 sorry I had another problem somebody turn the connectivity in the car off.
So I still have no glue that's your issue.
Can anybody of you make a screen share with me, so that I can analyze the issue?

bye

**Comment by Joker7555** [comment]
teamviewer?

On 24-2-2021 13:37:41, Konrad Mattheis <notifications@github.com> wrote:
@Kai-Angne [https://github.com/Kai-Angne] & @Joker7555 [https://github.com/Joker7555] sorry I had another problem somebody turn the connectivity in the car off.
So I still have no glue that's your issue.
Can anybody of you make a screen share with me, so that I can analyze the issue?
bye

**Comment by Joker7555** [comment]
814 010 050

7shg36

its open we can communicate in notepath
Sjakie

On 24-2-2021 14:14:12, Sjaak Koppejan <sjaak@koppejan.org> wrote:
teamviewer?

On 24-2-2021 13:37:41, Konrad Mattheis <notifications@github.com> wrote:
@Kai-Angne [https://github.com/Kai-Angne] & @Joker7555 [https://github.com/Joker7555] sorry I had another problem somebody turn the connectivity in the car off.
So I still have no glue that's your issue.
Can anybody of you make a screen share with me, so that I can analyze the issue?
bye

**Comment by konne** [comment]
@Kai-Angne & @Joker7555 
Hi, can you connect with the my Renault app https://play.google.com/store/apps/details?id=com.renault.myrenault.one.fr&hl=de&gl=US or https://apps.apple.com/de/app/my-renault-app/id1440073013 and your credentials?

bye

**Comment by Kai-Angne** [comment]
Hi @konne,

yes, i can connect with the Renault App for Android. Disconnected account and re-entered the (same) credentials. Works.

Thx a lot for your time and work!
Kai

**Comment by Joker7555** [comment]
Hi,
I cant log in.
According Renault The Netherlands is this app not for my car.
Thanks for your effort
Sjakie

On 1-3-2021 09:22:07, Kai Angne <notifications@github.com> wrote:
Hi @konne [https://github.com/konne],
yes, i can connect with the Renault App for Android. Disconnected account and re-entered the (same) credentials. Works.
Thx a lot for your time and work!
Kai

**Comment by konne** [comment]
@Joker7555 thanks for the test. This app uses the same API that this module is using. I will close the topic
