### ISSUE TITLE
Location: This feature is not technically supported by this gateway

### ISSUE THREAD

**Issue by dehsgr** [node-red-contrib/node-red-contrib-renault-ze#32]
**Description**
Requesting location info ends up in error 501: This feature is not technically supported by this gateway.

**To Reproduce**

1. Place a ze node on your flow.
2. Configure a debug node to output whole message.
3. Inject a timestamp into ze node.
4. See message output.

**Expected behavior**
I would expect correct location information.

**Sample**
>{
   "_msgid":"25e13355.7f1f5c",
   "payload":{
      "type":"TECHNICAL",
      "messages":[
         {
            "code":"err.tech.501",
            "message":"{\"errors\":[{\"status\":\"501\",\"code\":\"error.internal\",\"detail\":\"This feature is not technically supported by this gateway\"}]}"
         }
      ],
      "errors":[
         {
            "errorCode":"err.tech.501",
            "errorMessage":"{\"errors\":[{\"status\":\"501\",\"code\":\"error.internal\",\"detail\":\"This feature is not technically supported by this gateway\"}]}"
         }
      ],
      "error_reference":"TECHNICAL"
   },
   "topic":"location"
}

**Comment by konne** [comment]
@dehsgr
Which country you are based in?
Do you have enabled in the car that data transfer is allowed?

**Comment by dehsgr** [comment]
@konne, I'm located in Germany and data transfer is allowed.

**Comment by konne** [comment]
@dehsgr
Okay, what car do you have?
I have a Renault Zoe Sep. 2020, in it still works perfectly.

Can you please also try the send as topic, charge, or cockpit? Maybe the only location makes an issue?

**Comment by dehsgr** [comment]
It's an R240. Yes, only location makes an issue. Cockpit and charge are working.

**Comment by konne** [comment]
@dehsgr sorry no idea, because for my car it's working perfectly. You can search a little bit in the communities like pyZE,... if they have a hint. I'm happy to implement if I can, but unfortunately, I can only test my car.
The Renault API is unfortunately not consistent across countries and cars.

**Comment by IAlves2022** [comment]
Hello,

For what i've read about this issue, i have the same one, the location wont work on this Zoe, it's the Zoe 40?

I've tried with the Z40 and get the same error in location, and in the Z50, i can get all the info without errors.

Best regards

**Comment by konne** [comment]
Yes this is related so each car. So no issue of this package. I will close the issue
