### ISSUE TITLE
temperature

### ISSUE THREAD

**Issue by danpadure** [node-red-contrib/node-red-contrib-renault-ze#41]
Is the temperature always 20C?

**Comment by konne** [comment]
@danpadure can you please describe your question a little bit more?
What do you mean?
The return of a read-out temperature?
The default set temperature?

**Comment by danpadure** [comment]
the reported battery temperature seems to be always 20C?
even in the example in the readme file, the temperature is still 20C  :)

**Comment by konne** [comment]
okay, there you have to ask renault. This is the exact same JSON result that we get from the API gateway.
I expect this is not filled by renault.
I will close that issue because I can nothing do around that topic. Feel free to reopen if you still have an open question around that topic.
