### ISSUE TITLE
write access i.e. start/stop charging

### ISSUE THREAD

**Issue by ctr49** [node-red-contrib/node-red-contrib-renault-ze#45]
**Is your feature request related to a problem? Please describe.**
Apart from the information about current data (i.e. charge state) it would be great if charging could also be started/stopped via node-red.

**Describe the solution you'd like**
Make POST requests towards the API to also control the car rather than just monitoring it.

**Describe alternatives you've considered**
pyze already has write requests, but it doesn't integrate into node-red

**Comment by konne** [comment]
@ctr49  this is already possible with the msg.topic => set-charge-mode
and the correct payload.

See: https://github.com/node-red-contrib/node-red-contrib-renault-ze/blob/b90f99742c9661ca9693f62a9c7b2eefc59933a0/src/renault-ze.ts#L52

I will close this ticket. I you still have an issue, just reopen.
