### ISSUE TITLE
accounts.accounts is not iterable

### ISSUE THREAD

**Issue by marowsky** [node-red-contrib/node-red-contrib-renault-ze#53]
Hello,

First of all thank you for this work. Since yesterday I have this error: TypeError: accounts.accounts is not iterable
I have not been able to find the solution. 
Do you have an idea ? Thank you in advance

**Comment by PatrickM2201** [comment]
Hello, 
I have to say thank you for your great work, too! Since today approx. 10am I am getting the same error. I do not find any further hint for the root cause. Via the "My Renault" mobile app, there are no connection problems, all data is shown as usual.

Thank you in advance

**Comment by konne** [comment]
@marowsky @PatrickM2201 Renault has changed the API KAMEREON key. I updated via #54 and I expect that you can update tomorrow morning to 1.3.1 this should fix your issue.
If not please reopen the ticket

**Comment by PatrickM2201** [comment]
@konne, thank you for the very fast fix :-) I can confirm, it is working with 1.3.1.

**Comment by albertom75** [comment]
HY, i have the same problem how i can check ? thank you

**Comment by konne** [comment]
@albertom75  for me it is just working, no idea
