### ISSUE TITLE
Pause charging 

### ISSUE THREAD

**Issue by matzZz** [node-red-contrib/node-red-contrib-renault-ze#56]
Hi,
it is possible to send commands like Pause charging or turn on the heater?

**Comment by ovidiulaz7** [comment]
yes, you can, 
see the comments on this PR

https://github.com/node-red-contrib/node-red-contrib-renault-ze/pull/75

**Comment by matzZz** [comment]
> yes, you can, see the comments on this PR
> 
> #75

Thanks!
