### ISSUE TITLE
TypeError: accounts.accounts is not iterable

### ISSUE THREAD

**Issue by eRudy** [node-red-contrib/node-red-contrib-renault-ze#57]
Hi,

Thanks for this great node.

I often see the error "**_TypeError: accounts.accounts is not iterable" in the console_**"

I think it's caused by Renault API being unavailable.

Could it be possible to catch this error and return a specific payload (to be used in the flow for notification for exemple) ?

Have a nice day !

Rudy

**Comment by konne** [comment]
@eRudy just update the version.

**Comment by eRudy** [comment]
> @eRudy just update the version.

I forget to mention I'm already in 1.3.1, and still have the issue multiple times per day.

**Comment by konne** [comment]
if it is sometimes working, I expect that is an issue from the Renault sometimes.
I can not to anything about that
