### ISSUE TITLE
Response error from Renault Zoe node

### ISSUE THREAD

**Issue by pvgent1** [node-red-contrib/node-red-contrib-renault-ze#62]
**Describe the bug**

FetchError: invalid json response body at https://renault-wrd-prod-1-euw1-myrapp-one.s3-eu-west-1.amazonaws.com/configuration/android/config_en_GB.json reason: Unexpected token < in JSON at position 0

**To Reproduce**

Inject node with timestamp
Node configured with username and password

**Expected behavior**

JSON payload with attributes

**Screenshots**

**Version (please complete the following information):**
1.3.1

- Browser: [e.g. chrome, safari]
- Node-Red: [e.g. 1.x]
V2.2.2

**Additional context**

**Comment by octavianrusu** [comment]
I have the same problem, it started the day before yesterday.
msg : error
"FetchError: invalid json response body at https://renault-wrd-prod-1-euw1-myrapp-one.s3-eu-west-1.amazonaws.com/configuration/android/config_en_GB.json reason: Unexpected token < in JSON at position 0"
arted the day before yesterday

**Comment by Kai-Angne** [comment]
Same here, but Android My Renault App didn't work either. ZoePHP with the same credentials did work. As far as I remember this error did appear not the first time and might be due to a server problem on Renault side.

**Comment by pvgent1** [comment]
My Renault app on iPhone doesn't work (Server error). Zeddy app on iPhone works fine.

**Comment by konne** [comment]
@pvgent1 @Kai-Angne @octavianrusu
I added a fallback if the renault server is not available. This is also the reason that the renault app is not working.

Update to the new 1.3.2 release
