### ISSUE TITLE
Node-RED integration no longer working

### ISSUE THREAD

**Issue by GwelforBodad** [node-red-contrib/node-red-contrib-renault-ze#85]
**Describe the bug**
It looks like there's been a change on the Renault website since neither this Node-RED contrib nor the Home Assistant integration is working.

**To Reproduce**
Inject charge mode (or any previously working parameter) into the contrib node with correct credentials fails

**Expected behavior**
Doing the above would result in valid data in the subsequent debug node

**Screenshots**
Debug message "TypeError: accounts.accounts is not iterable"

**Version (please complete the following information):**

- OS: Win11
- Browser: Edge
- Node-Red: V3.0.2

**Additional context**

**Comment by JapieG** [comment]
same problem. What is going on.

**Comment by lksp1** [comment]
Renault has changed it's api key. I've create a pull request for the new API key.
Should work again when it's accepted and released.

**Comment by RoulstoneR** [comment]
Also having the same issue.

**Comment by lksp1** [comment]
As workaround (until pull request is accepted and published) you can update the api key on your local machine yourself. 
As exaple the required steps for a Linux environment:

1. open file /home/[user]/.node-red/node_modules/node-red-contrib-renault-ze/nodes/ZEServices.js
2. replace 2 occurences of VAX7XYKGfa92yMvXculCkEFyfZbuM7Ss with YjkKtHmGfaceeuExUDKGxrLZGGvtVS0J and save the file
3. restart NodeRed using command "node-red-restart"

**Comment by JapieG** [comment]
thanks @lksp1 ! This is indeed the solution.

**Comment by konne** [comment]
Updated, should work now
![image](https://user-images.githubusercontent.com/1100969/232975968-3aa5f33e-dd1b-4f00-a236-bdb4d5c64c63.png)
