### ISSUE TITLE
Renault has changed API access?

### ISSUE THREAD

**Issue by bbking78** [node-red-contrib/node-red-contrib-renault-ze#88]
**Describe the bug**
this is not a bug report regarding this node, but rather asking if someone knows whats going on? The node is not receiving values any more (message: "{"errors":[{"status":"403","code":"security.access","detail":"Access is denied for this resource"}]}") and the smartphone app is not showing values either.

**To Reproduce**
please open your phone app or look into the node values and check if you can see anything.

**Expected behavior**
Of course I am looking for a solution to get this going again.

**Screenshots**
![grafik](https://github.com/node-red-contrib/node-red-contrib-renault-ze/assets/34800222/7e7cdcd7-1c34-447b-894e-3d39950feee5)

**Version (please complete the following information):**
- Node-Red node: 1.4.2

**Additional context**
the website https://www.services.renault-ze.com/#/user/login seems to be gone, also.

**Comment by konne** [comment]
should be solved, I just use the current version and it works
